global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'quarkus'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'host.docker.internal:8081'
        - 'host.docker.internal:8191'
        - 'host.docker.internal:8192'
        - 'host.docker.internal:8193'